
import "./globals.css";
import Head from "next/head";


export const metadata = {
  title: "Agência Desing Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">

    
      <body>

        

        {children}
      </body>
    </html>
  );
}
